# Generated by Django 3.1.14 on 2023-05-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiWordsTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkWord', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='allMandD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfRadio', models.CharField(max_length=32)),
                ('timePoints', models.CharField(max_length=256)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='allMistakesNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfRadio', models.CharField(max_length=32)),
                ('date', models.DateField(null=True)),
                ('details', models.CharField(max_length=128)),
                ('keyword', models.CharField(default='default', max_length=32, null=True)),
            ],
        ),
    ]
